In [2]:
from sklearn.linear_model import LinearRegression

In [3]:
import numpy as np

In [4]:
from sklearn.datasets import fetch_california_housing

In [5]:
house =  fetch_california_housing()

In [6]:
house

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [7]:
X = house.data
y = house.target

In [8]:
X

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [9]:
linear_reg = LinearRegression()

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(X, y)

In [12]:
linear_reg.fit(x_train, y_train)

LinearRegression()

In [13]:
import matplotlib.pyplot as plt

In [14]:
linear_reg.score(x_test, y_test)

0.6103604860193246

In [15]:
from sklearn.metrics import mean_squared_error

In [16]:
mean_squared_error(y_test, linear_reg.predict(x_test))

0.5028380365551925

In [17]:
from sklearn.metrics import r2_score

In [18]:
r2_score(y_test, linear_reg.predict(x_test))

0.6103604860193246

In [19]:
from sklearn.metrics import mean_absolute_error

In [20]:
mean_absolute_error(y_test, linear_reg.predict(x_test))

0.5268724470082607

In [21]:
from sklearn.metrics import root_mean_squared_error

In [22]:
root_mean_squared_error(y_test, linear_reg.predict(x_test))

0.7091107364546052

## 多项式回归

In [23]:
x = np.random.uniform(-4,2, size=100)

In [34]:
y = 2*x**2 + 4*x + np.random.randn(100)

In [35]:
X = x.reshape(-1,1)

In [26]:
X_2 = X**2

In [27]:
data = np.hstack((X, X_2))

In [28]:
LinearReg = LinearRegression()

In [29]:
LinearReg.fit(data, y)

LinearRegression()

In [30]:
LinearReg.coef_

array([3.90442212, 1.98141252])

In [31]:
from sklearn.preprocessing import PolynomialFeatures

In [36]:
X

array([[-3.1484747 ],
       [ 1.96020457],
       [ 0.18812407],
       [ 1.67657165],
       [ 1.94488276],
       [ 1.53579657],
       [-0.42080919],
       [-3.41848637],
       [-0.61369982],
       [-0.02508029],
       [-1.81887299],
       [ 0.47965282],
       [ 0.09130998],
       [ 1.90930962],
       [ 0.00893517],
       [ 0.98780105],
       [ 1.6706276 ],
       [ 1.12606653],
       [-3.88600987],
       [ 0.36330989],
       [ 1.69668674],
       [-1.79142209],
       [ 0.99331704],
       [ 0.8575304 ],
       [-0.5416763 ],
       [ 1.01108426],
       [ 1.74165053],
       [-0.02990547],
       [-0.12324046],
       [ 1.70638566],
       [-1.0212762 ],
       [ 0.9236321 ],
       [-3.68825322],
       [-0.86727219],
       [ 1.71673978],
       [-3.44709143],
       [-2.32774821],
       [-3.66326939],
       [-2.09223408],
       [ 0.71727345],
       [-3.25728245],
       [-1.12070727],
       [ 0.45064136],
       [-1.41664118],
       [-0.04595856],
       [-0

In [32]:
poly = PolynomialFeatures(degree=2)

In [38]:
poly.fit(X)

PolynomialFeatures()

In [39]:
data = poly.transform(X)

In [43]:
x_train, x_test, y_train, y_test = train_test_split(data, y, test_size=0.7, random_state=42)

In [44]:
linear_reg.fit(x_train, y_train)

LinearRegression()

In [45]:
linear_reg.score(x_test, y_test)

0.9613509655842188