In [7]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline

import numpy as np
import matplotlib.pyplot as plt

In [16]:
iris = load_iris()
X = iris.data
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
y[y==2]=1

In [18]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
x_train, x_test, y_train, y_test = train_test_split(X, y)

model = make_pipeline(
    # StandardScaler(),
    LogisticRegression(),
)
model.fit(x_train, y_train)

Pipeline(steps=[('logisticregression', LogisticRegression())])

In [20]:
model.score(x_test, y_test)

1.0

In [21]:
y_pred = model.predict(x_test)

In [22]:
TP = y[y ==0]

In [45]:
TN = np.sum((y_pred == 0) & (y_test == 0))
TP = np.sum((y_pred == 1) & (y_test == 1))
FP = np.sum((y_pred == 1) & (y_test == 0))
FN = np.sum((y_pred == 0) & (y_test == 1))
print(TP, TN, FP, FN)


26 12 0 0


In [30]:
confusion_matrix = np.array([
    [TP, FP],
    [FN, TN]
])

In [31]:
confusion_matrix

array([[26,  0],
       [ 0, 12]])

In [32]:
precision = TP / (TP + FP)

In [33]:
precision

np.float64(1.0)

In [37]:
accuracy = (TP+TN)/(TP+TN+FP+FN)

In [38]:
accuracy

np.float64(1.0)

In [39]:
recall = TP/(TP+FN)

In [40]:
from sklearn.metrics import accuracy_score

In [41]:
accuracy_score(y_test, y_pred)

1.0

In [55]:
from sklearn.metrics import confusion_matrix

In [56]:
confusion_matrix(y_test, y_pred)

array([[12,  0],
       [ 0, 26]])

In [47]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred)

1.0

In [48]:
from sklearn.metrics import precision_score
precision_score(y_test, y_pred)

1.0

In [52]:
confusion_matrix = np.array([[TP, FN], [FP, TN]])

In [53]:
confusion_matrix

array([[26,  0],
       [ 0, 12]])

In [51]:
confusion_matrix

[[np.int64(26), np.int64(0)], [np.int64(0), np.int64(12)]]